# -*- coding: utf-8 -*-
"""HW3quicksort.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_vP4zOScG8ZTeIkhrjRKlw6ZWdY8iZlC
"""

demo = [33, 67, 8, 13, 54, 119, 3, 84, 25, 41]

def quicksort(demo, start, end): 
  if start>= end : #如果左大於右,就跳出
    return
  i = start #左邊的指標             
  j = end  #右邊的指標 
  pivot = demo[start]  #以左邊為基準點      #寫法參考網路上ramonliao在iT1邦幫忙的文章
  while i !=j:
    while demo[j] >pivot and i<j:#從右開始找,找比基準小的值
      j -= 1
    while demo[i] <=pivot and i<j:#從左開始找,找比基準大的值
      i += 1
    if i<j: #當左右指標沒有相遇時，交換值
      demo[i], demo[j] = demo[j], demo[i]
  
  demo[start] = demo[i]   #將基準點歸至指標相遇點
  demo[i] = pivot
  quicksort(demo,start,i-1)#繼續處理指標相遇點左邊子循環
  quicksort(demo,i+1, end)#繼續處理指標相遇點右邊子循環
quicksort(demo,0, len(demo)-1)
demo

